### ISSUE TITLE
Install all external dependencies with conda

### ISSUE THREAD

**Issue by jmoldon** [AMIGA-IAA/enhance-diffuse#2]
We will need to manage all the dependencies with conda.

**Comment by sebastian-luna-valero** [comment]
Here is the list:
* swarp: https://anaconda.org/conda-forge/astromatic-swarp
* astropy: https://anaconda.org/conda-forge/astropy
* pyfits: https://anaconda.org/search?q=pyfits
* sextractor: https://anaconda.org/conda-forge/astromatic-source-extractor

Pending:
* GNU Astro/NoiseChisel: https://github.com/conda-forge/staged-recipes/pull/9723

**Comment by sebastian-luna-valero** [comment]
And finally we have GNU Astro as well:

https://anaconda.org/conda-forge/gnuastro

**Comment by sebastian-luna-valero** [comment]
Added a conda environment file in https://github.com/AMIGA-IAA/enhance-diffuse/commit/b4fb8e7a1197de26a3c5a19c082e8a97ff5f4a90

**Comment by sebastian-luna-valero** [comment]
FYI, added travis-ci tests in https://github.com/AMIGA-IAA/enhance-diffuse/commit/4d14e67a5f35fa4e8f290235ccaa509ab0250415

Happy to go into the details in person in our next meeting
